{% set name = "biosiglive" %}
{% set version = "2.0.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/79/f3/98ca426880fc449c744cfaa5ba0401b5a2c01ee602f59e3d9c41d989988b/biosiglive-2.0.3.tar.gz
  sha256: a9bb7a11b4bd032bd690606b0713d95c85640842ce7c5b1b12600e991b94de62

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - hatchling
    - python >=3.9
  run:
    - python >=3.9
    - matplotlib-base
    - numpy
    - scipy
    - pyqtgraph
    - pyqt
    - pyopengl


test:
  commands:
    - xvfb-run python -c "import biosiglive"  # [linux]
  imports:
    - biosiglive  # [not linux]
about:
  home: "https://github.com/pyomeca/biosiglive"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A Python package for real-time streaming and processing of biomechanical data"
  doc_url: https://github.com/pyomeca/biosiglive/blob/master/README.md
  dev_url: https://github.com/pyomeca/biosiglive

extra:
  recipe-maintainers:
    - aceglia
